### ISSUE TITLE
Safari Extension

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/SteamDatabase#170]
Mostly requires rewriting chrome's manifest.json to safari format.

**Comment by Takohashi** [comment]
Are there any new plans for the Safari Extension? :/

**Comment by Arnoud-B** [comment]
Still only 3%?

**Comment by xPaw** [comment]
I'm not going to pay apple for a dev license and an apple device to publish there.

Safari add-on is not happening.

**Comment by Arnoud-B** [comment]
Thanks for the clarity, totally understand your point of view.

Perhaps a consideration: putting a price on the extension could earn you back the dev license + time invested. You'd need a significant amount of Safari users though..

**Comment by yaakov-h** [comment]
... a lot more than 3%.
