### ISSUE TITLE
Add way to see what games are on your wishlist

### ISSUE THREAD

**Issue by humdogm** [SteamDatabase/SteamDatabase#243]
Some people have big wishlists, and they don't always go down their wishlist when viewing sales and the like. An indicator for the relevant games could help people find and purchase games that they have wanted in the past. (Also, it's not practical to go down your wishlist everyday during a sale.)

**Comment by janreggie** [comment]
>there's no API to get user's wishlist

[There is now](https://stackoverflow.com/a/56021201/14020202). I do hope that this gets implemented someday.

**Comment by xPaw** [comment]
It is now possible to filter your wishlist: https://steamdb.info/sales/?displayOnly=Wishlist

**Comment by humdogm** [comment]
This feature is a long time coming! Like wow, I made this issue back when I was in high school; I am at a very different point in my life now. 
Thanks for closing on this!
