### ISSUE TITLE
Wrong flag icon for the CIS

### ISSUE THREAD

**Issue by Szaki** [SteamDatabase/SteamDatabase#291]
Hello!
I think you should give the CIS its own flag in the store prices segment instead of having Azerbaijan's flag.
![cis](https://cloud.githubusercontent.com/assets/10335149/5565906/855cfa9e-8f0f-11e4-9d06-fce69a7dec73.png)
There's the flag of the CIS
https://en.wikipedia.org/wiki/Flag_of_the_Commonwealth_of_Independent_States

**Comment by nyakze** [comment]
Why not use CIS flag instead? It makes much more sense than using AZ for the whole region.

**Comment by xPaw** [comment]
Read my reply please. The flag indicates which country we use to get prices.
