### ISSUE TITLE
SteamDatabaseBackend pooling issue

### ISSUE THREAD

**Issue by TheAnthonyNL** [SteamDatabase/SteamDatabase#295]
The timeout period elapsed prior to obtaining a connection from the pool.  

This may have occurred because all pooled connections were in use and max pool size was reached.

Any idea how to solve this?

**Comment by xPaw** [comment]
Well you can try increasing timeouts and pool size. If you feel adventurous, you can try debugging and see if this happens at some specific place.

**Comment by TheAnthonyNL** [comment]
Happens always on ::

public static MySqlDataReader ExecuteReader(string text, params MySqlParameter[] parameters)
        {
            return MySqlHelper.ExecuteReader(Settings.Current.ConnectionString, text, parameters);
        }

        public static int ExecuteNonQuery(string text, params MySqlParameter[] parameters)
        {
            return MySqlHelper.ExecuteNonQuery(Settings.Current.ConnectionString, text, parameters);
        }

note: im using xampp (couldn't find the pool or timeout settings yet in php/mysql or apache ini files)

**Comment by xPaw** [comment]
Can you get a proper stacktrace?

**Comment by TheAnthonyNL** [comment]
MySql.Data.MySqlClient.MySqlException was unhandled by user code
  HResult=-2147467259
  Message=error connecting: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
  Source=MySql.Data
  ErrorCode=-2147467259
  Number=0
  StackTrace:
       bij MySql.Data.MySqlClient.MySqlPool.GetConnection()
       bij MySql.Data.MySqlClient.MySqlConnection.Open()
       bij MySql.Data.MySqlClient.MySqlHelper.ExecuteReader(String connectionString, String commandText, MySqlParameter[] commandParameters)
       bij SteamDatabaseBackend.DbWorker.ExecuteReader(String text, MySqlParameter[] parameters) in c:\Users\A\Desktop\SteamDatabaseBackend-master\Util\DbWorker.cs:regel 25
       bij SteamDatabaseBackend.SubProcessor.Process(PICSProductInfo productInfo) in c:\Users\A\Desktop\SteamDatabaseBackend-master\Processors\SubProcessor.cs:regel 42
       bij SteamDatabaseBackend.PICSProductInfo.<>c__DisplayClasse.<<OnPICSProductInfo>b__3>d__17.MoveNext() in c:\Users\A\Desktop\SteamDatabaseBackend-master\Steam\PICSProductInfo.cs:regel 86
  InnerException:

**Comment by xPaw** [comment]
And does it always happen there?

Anyway, there's not much I can do, you will need to tweak options yourself.

**Comment by TheAnthonyNL** [comment]
@xPaw  yes it always happens there exactly. 

And ok will see what i can do.
