### ISSUE TITLE
Add a way to find multi-pack deals such as BL2 4-Pack, Cubemen 2 2-pack...

### ISSUE THREAD

**Issue by comp9** [SteamDatabase/SteamDatabase#296]
Every few months I check around on the site for a way to find all the multi-packs on Steam. A lot of games have 2, 3, 4, or 5 pack deals. You can get a pretty significant deal buying the multi-pack. Would it be possible to add finding multi-packs as a feature?

**Comment by xPaw** [comment]
I don't think we will be able to do something like this in a reliable or accurate manner.

**Comment by TomasDuda** [comment]
You can use sub key search [like this](https://steamdb.info/search/?a=sub_keynames&keyname=14&operator=5&keyvalue=0) to get packages which grant more copies. The list also includes guest passes which expire.

You need to be signed in to use advanced search.

**Comment by comp9** [comment]
@xPaw Thanks for the reply.

@ThomasDuda Thanks, that works well! I'll use that method for now.
