### ISSUE TITLE
SteamDB Chrome Extension - Hide Uninterested Breaks Wishlist

### ISSUE THREAD

**Issue by Daedhart** [SteamDatabase/SteamDatabase#301]
If you check the "Hide products on sales page that you are not interested in" box in the SteamDB Chrome extension, it seems to target wishlisted games instead; nothing on the sales page will be highlighted blue and not-interested games will still be present.

**Comment by xPaw** [comment]
Weird. We're only hiding stuff from `rgIgnoredApps` and `rgIgnoredPackages` arrays that are returned from Steam.

**Comment by Daedhart** [comment]
Turns out theres more going on here than I thought. The issue I saw now looks to be more of the website not pulling the desired config from the extension under certain conditions rather than the extension itself being broken. If I can pinpoint anything more specific to look at, Ill open another bug report.

**Comment by xPaw** [comment]
```
Mixed Content: The page at 'https://steamdb.info/sales/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://store.steampowered.com/dynamicstore/userdata/'. This request has been blocked; the content must be served over HTTPS.
```

This seems to be the problem. Which happens because of this:
```
Request URL:https://store.steampowered.com/dynamicstore/userdata/
Request Method:GET
Status Code:302 Moved Temporarily

Location:https://store.steampowered.com/login/checkstoredlogin?redirectURL=%2Fdynamicstore%2Fuserdata%2F
```

**Comment by xPaw** [comment]
Okay this issue is reproducible, I've emailed some Valve guys about the issue *(checkstoredlogin redirects to http instead of https)*. Meanwhile, I will see if I can add a simple hack-fix.

**Comment by xPaw** [comment]
Valve supposedly fixed this issue.
