### ISSUE TITLE
Display Packages/SUBIDs associated with account

### ISSUE THREAD

**Issue by Abana** [SteamDatabase/SteamDatabase#310]
I just skip the part with the praise and how much I like SteamDB and how useful it is etc. pp. (I think that is obvious) and save us the time.

So, my suggestion:

An overview with the SUBIDs tied to the account, similar to the 'My Apps' page (https://steamdb.info/myapps/).

That would be very useful, I think.

**Comment by xPaw** [comment]
There are no public APIs that allow us to get which packages you own.

**Comment by Abana** [comment]
Oh, I didn't know that. What a bummer.

I thought that setting your Steam profile to public would be sufficient.

So only the APPIDs are publicly available, while the SUBID is only stored internally or just on the client-side, right?

How do you get your packages then? Isn't there some kind of Steam console?

**Comment by xPaw** [comment]
You can do `steam://open/console` and use `licenses_print` command.

**Comment by Abana** [comment]
Ah, thank you!

I just found it, too.
A nice list of all Steam commands and parameters: https://gist.github.com/davispuh/6600880

`licenses_for_app - <appid> : shows active licenses for appid`
`licenses_print - display users's Steam3 licenses`

I also found this one: https://lab.xpaw.me/license-parser.html

It is your site, right? ;)
