### ISSUE TITLE
New filters suggestion for Sales page

### ISSUE THREAD

**Issue by enchained** [SteamDatabase/SteamDatabase#314]
1. Option to hide all non-lowest recorded deals.
When I'm looking through deals I usually skip grey deals and consider only green ones.

2. Option to show only games with n+ percents in reviews, to eliminate the worst ones. Also needs a minimal number of reviews to consider objective to be filtered out.

3. Option to show only deals that will expire soon (in a day, 12h, something like that). Useful for last minute shopping, if you don't want to miss a thing before deals will change for new ones.

**Comment by xPaw** [comment]
All these can be achieved by simply sorting the table. I really don't want to be adding a bunch of filtering options like this which will only complicate the code.

@Marlamin @TomasDuda what do you guys think?

**Comment by TomasDuda** [comment]
It's useless, you can use sorting for all of your suggestions.

**Comment by enchained** [comment]
@xPaw @TomasDuda You're right, (3) can totally be achieved using just sorting. 

But what about two others? 

For (2), [I've seen some demand](http://www.reddit.com/r/GameDealsMeta/comments/2vq9ha/search_steam_for_games_with_a_certain_postivity/) for being able to see the best deals for the best games specifically, and I wasn't able to recreate that just by using sorting. I can sort first by rating, then by discount, and still all I can see are reviews sorted inside every percent separately and that is not helping at all with all those -86, -85, -76, -75 etc ([pic example here](https://docs.google.com/file/d/0B_ddI4kCmF52S3ExV1dNRjhCSHc/preview)). Is there any better way for it that I don't know of?

As for the matter of (1), I don't think it will complicate anything much. Just a similar checkbox under "Show wishlisted only" that will hide games with discounts that have "not-lowest" css class. 
And I don't see any sorting-related resolution for (1) for the moment, either.
