### ISSUE TITLE
Custom markers in player graphs

### ISSUE THREAD

**Issue by GranPC** [SteamDatabase/SteamDatabase#330]
I think it'd be interesting to be able to mark certain points in the player graphs in SteamDB, just like the 'new data storage method' thing. Would be cool to see how many new players games get from Mac/Linux releases, sales, etc.

**Comment by xPaw** [comment]
This could also be used for automatic markers like free weekends, game releases, and manual ones like CS:GO/Dota championships.

Probably would need to have 2 types of markers, a single line, and something like a range (free weekends, sales, championships).

**Comment by xPaw** [comment]
Shipt, need to add some admin interface though.

https://steamdb.info/app/570/graphs/
https://steamdb.info/app/730/graphs/

**Comment by GranPC** [comment]
Holy shit this is great

**Comment by GranPC** [comment]
:+1:

**Comment by Marlamin** [comment]
![itshappening](https://cloud.githubusercontent.com/assets/50212/6656927/410bf3b0-cb3a-11e4-98ef-f2789cc99057.gif)

**Comment by xPaw** [comment]
Interface is :ship:
