### ISSUE TITLE
Error: For this website to function correctly you must unblock cdnjs.cloudflare.com

### ISSUE THREAD

**Issue by Sanomas** [SteamDatabase/SteamDatabase#335]
Hey...

.. With browsing the https://steamdb.info website I'm getting this error: 

For this website to function correctly you must unblock cdnjs.cloudflare.com

Specially on the Sales page and I can't sort out in order of Price or game (or others)... but I don't know how to fix this.

Please help me to fix it, thank you in the advance :-)

**Comment by xPaw** [comment]
Do you use any extensions that block third-party javascript or something?

Try [opening javascript console](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers/77337#77337) and see if there are any errors.

**Comment by Sanomas** [comment]
Thanks for the reply xPaw... I use Adblock Plus and HTTPS Everywhere and my browser is Google Chrome... The Adblock Plus has been disabled for that site but for some reason the HTTPS extension is been enabled.

When I tried to open javascript console in the steamdb.info so I've got these error's so far:


Failed to load resource: net::ERR_CONNECTION_RESET https://cdnjs.cloudflare.com/ajax/libs/octicons/2.2.2/octicons.woff
Failed to load resource: net::ERR_CONNECTION_RESET https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js
Failed to load resource: net::ERR_CONNECTION_RESET https://cdnjs.cloudflare.com/ajax/libs/jquery-timeago/1.4.1/jquery.timeago.min.js
Failed to load resource: net::ERR_CONNECTION_RESET https://cdnjs.cloudflare.com/ajax/libs/authy-forms.css/2.2/images/flags.png
Failed to load resource: net::ERR_CONNECTION_RESET https://cdnjs.cloudflare.com/ajax/libs/octicons/2.2.2/octicons.ttf
Failed to load resource: net::ERR_CONNECTION_RESET https://cdnjs.cloudflare.com/ajax/libs/octicons/2.2.2/octicons.svg#octicons

As you see there's a few...

**Comment by xPaw** [comment]
Something (most likely an extension) is blocking it.

**Comment by Sanomas** [comment]
I see, I disabled them all... and still got the error in the site AND the console... don't know what to do!

But is it something to do with my region? I'm from Iran.

Take a note here, I have the same error in the Firefox and Opera too... Firefox with only FlashGot plugin, but Opera with the same extensions as using (and been disabled there too) in the Google Chrome.

**Comment by xPaw** [comment]
What happens if you try to visit https://cdnjs.cloudflare.com/ajax/libs/authy-forms.css/2.2/images/flags.png directly?

**Comment by Sanomas** [comment]
Nothing happen, nothing is showing...

**Comment by xPaw** [comment]
Sounds like Iran might be doing something funky with it.

cc @Benjojo, maybe he knows more.

**Comment by Sanomas** [comment]
I'm not sure if they black-ed the IP from here, because with use the Proxy (and having a different IP to free the Internet) I still have the same error...

**Comment by xPaw** [comment]
Do you have a crappy firewall/antivirus on your PC?
