### ISSUE TITLE
Some game reviewes are missing on the sales page

### ISSUE THREAD

**Issue by enchained** [SteamDatabase/SteamDatabase#336]
Games like Commandos 3: Destination Berlin, Commandos: Behind Enemy Lines, Gravity Badgers, Talisman: Digital Edition, Infinity Runner and a lot of others show "-" in their Rating column. However, they do have reviews on Steam. 

This is a recent bug, I think. Also, maybe it's not related, but this weird thing started a couple days ago: when I load a Steam page of a game, the review section (the one above the tags) is often missing at all (while there still are reviews down the page). A few page refreshes fixes it.
Is there something globally bugged with Steam reviews?

**Comment by xPaw** [comment]
> when I load a Steam page of a game, the review section (the one above the tags) is often missing at all (while there still are reviews down the page). A few page refreshes fixes it.

That would perfectly explain why it's missing from SteamDB.
