### ISSUE TITLE
Display mod actions in forum topics

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/SteamDatabase#343]
I've added actionid in user log, but existing events need to be converted.

**Comment by xPaw** [comment]
Added them, still need to convert existing events whenever we push to prod.

**Comment by xPaw** [comment]
Perhaps replies should display delete event, instead of hiding it. Would also make sense adding a reason field.

**Comment by TomasDuda** [comment]
Make a select box with reasons like "you're a poophead, RJ" and "duck off, Steam account seller".

**Comment by xPaw** [comment]
:nail_care:
