### ISSUE TITLE
Source Server Query to get SteamID or Nick name

### ISSUE THREAD

**Issue by Cludas18** [SteamDatabase/SteamDatabase#347]
Hi I was wondering if there was a way to get a players SteamID or in game name (for Garry's Mod) rather than just their Steam name. I've tried using $player['ID'] but as a comment in one of the files says, it just gives 0 or nothing.

**Comment by xPaw** [comment]
This is not related to SteamDB in any way.

**Comment by Cludas18** [comment]
My bad I was reading a different post and clicked new issue. I didn't realise it posted here.

I've never used GitHub :/ sorry

**Comment by DoctorMcKay** [comment]
Also, the answer is no.

**Comment by Cludas18** [comment]
So like, there's no way I could run a command to ban  a player using data from the $player fields? Because most of the time banning is done by their SteamID or Nickname

**Comment by DoctorMcKay** [comment]
No, because the SteamID is not in that response. Wishing it were so does not make it so.

Use rcon to run `status` then parse the output.

**Comment by Cludas18** [comment]
Ok. Any tips on how to do that?

**Comment by DoctorMcKay** [comment]
Google.

**Comment by Cludas18** [comment]
Mkay
