### ISSUE TITLE
Supported Systems not mathcing store oslist

### ISSUE THREAD

**Issue by Basaltq** [SteamDatabase/SteamDatabase#354]
You can see this in action:
https://steamdb.info/app/219150/config/
https://steamdb.info/app/261180/config/

I'm assuming this is all automated so why the mismatch?

**Comment by xPaw** [comment]
It's how developers mark it, there are at least three different support OS flags that have to be updated. It's out of our control.

**Comment by Basaltq** [comment]
Well the method you are currently using is clearly incorrect.

**Comment by xPaw** [comment]
We're simply displaying oslist in appinfo, you can go poke game developers to fix it.

**Comment by Basaltq** [comment]
Alright thanks. After watching at the app info I see what you are saying.
