### ISSUE TITLE
Forum: rate limits aren't being declared clearly to user for new threads

### ISSUE THREAD

**Issue by wickedplayer494** [SteamDatabase/SteamDatabase#356]
Instead of displaying a message along the lines of "you're posting new threads too fast, try again in a while", the message returned is an undescriptive "Something went wrong" message, which doesn't give users much of an idea as to what's wrong unless they can deduce that they're trying to post 2 threads and they're likely getting rate limited.

**Comment by xPaw** [comment]
Fixed.
