### ISSUE TITLE
Autobuy stops buying health at 300k

### ISSUE THREAD

**Issue by ChangedNameTo** [SteamDatabase/SteamDatabase#357]
The autobuy stops at energy shields 2, which is not enough to sustain through the night

**Comment by Marlamin** [comment]
Yeah this should probably be increased after a certain level. We're dying quick now. :skull: :skull: :skull:

**Comment by allthefoxes** [comment]
Intended

https://www.allthefoxes.me/img/12-KwMk6URX.png

**Comment by rossengeorgiev** [comment]
well spotted
![a](https://cloud.githubusercontent.com/assets/2720787/8194648/dd19611a-1474-11e5-909f-7e5842707a80.png)

**Comment by ChangedNameTo** [comment]
It should still upgrade though, now that we are wormholing up people are dropping left and right

**Comment by allthefoxes** [comment]
I've never dropped below max for more than a tick or two

**Comment by chauffer** [comment]
Hello? This is SteamDatabase, not steamSummerMinigame.
Go home everyone.

**Comment by Marlamin** [comment]
oh shit

**Comment by Marlamin** [comment]
![image](https://cloud.githubusercontent.com/assets/50212/8194676/757cc3ae-147d-11e5-85d0-6fa15e989d1d.png)
