### ISSUE TITLE
Average price per hour calculation is wrong

### ISSUE THREAD

**Issue by aEnigmatic** [SteamDatabase/SteamDatabase#362]
Atleast it's not $total_value / $total_hours.
It also isn't $sales_value / $total_hours, etc.

I'm pretty sure the number is more or less useless atm. (It's off by more than 90% for me)

**Comment by xPaw** [comment]
Can you show some examples where you think it's wrong?

**Comment by aEnigmatic** [comment]
https://steamdb.info/calculator/76561198012697915/?cc=us
[average price per hour] is displayed as $6.51

[total value] / [total hours]  =~ $4.21
[sales value] / [total hours] =~ $1.02
[avg. price] / [avg. hours]   =~ $1.70 (only played games, I guess?)

**Comment by xPaw** [comment]
It's actually `total prices per hour summed up` divided by `games owned`

**Comment by aEnigmatic** [comment]
Im not sure I follow.
What is `total prices per hour summed up`?

**Comment by aEnigmatic** [comment]
Im not sure I follow.
What is `total prices per hour summed up`?

**Comment by xPaw** [comment]
It's price/hour column added up.

**Comment by aEnigmatic** [comment]
Ahh, that explains it. You add pseudo-counts to the time played.
Not sure I agree with the definition, but at least nothing is broken.
