### ISSUE TITLE
Feature request: Library size/depot estimate

### ISSUE THREAD

**Issue by sigoshi** [SteamDatabase/SteamDatabase#364]
While going through the grueling process of migrating my steam library to a new hard drive this morning, and trying to figure out whether or not i finally had enough room to install my whole library, I realized that a potentially useful feature for the SteamDB calculator would be something that calculates the depot size and from that, the necessary disk space for the games in your library. 

With this feature, one could easily look up their library, and figure out (amongst many other findings,) whether or not they need to dedicate an entire hard drive to their video games. I realize that this would be easy for smaller, single-platform, single-language, and indie games (which have less depots in the list), but that a challenge is posed by games with multiple depots that arent used by every user. Depots that would be commonly unused are ones for other platforms (since windows, osx, and linux depots are listed separately), and ones for other languages. To prevent calculating depots that are unused, If this feature is added, choices similar to the currency type choice involving OS/platform and language should be used so that viewers can read the size of just what they need. these choices should only affect the size calculations, as one might still want to know the price of all games, but only know the size of what they can install on linux, for example. Additionally, It would probably need a disclaimer that such a feature only calculates install size, not any addons, since commonly modified games such as Garry's Mod and Skyrim can obviously grow well past their install size.

**Comment by xPaw** [comment]
You're also forgetting DLC depots, and depots that are only owned by certain packages. So doing this in calculator won't work, we would need to get your owned packages and work it out from there, but it's not worth the effort.
