### ISSUE TITLE
No link to Flattr from Donate page - is it authentic?

### ISSUE THREAD

**Issue by kparal** [SteamDatabase/SteamDatabase#365]
Hello,
I've been donating to you for a long time through Flattr:
https://flattr.com/thing/2054053/Steam-Database

However, today I looked at your donate page and there's no link to this Flattr item:
https://steamdb.info/donate/

The Flattr page also does not indicate a verified owner. That begs the question - is that Flattr item really yours, or have I been sending money to someone else for a long time?

In case it is yours, don't you want to add a link from your Donate page to this Flattr item, so that people can verify that it is really your account (or verify the owner through Flattr)?

Thanks.

**Comment by xPaw** [comment]
We did use Flattr, and yes that is our page, however we've switched to PayPal since then.

**Comment by kparal** [comment]
Thanks for reply.

Does this mean that you no longer receive the funds from the people that are subscribed to that Flattr page?

And if you still do, why don't you simply advertise both options on the Donate page, so that you're able to reach wider audience?

**Comment by xPaw** [comment]
Our received funds are still sitting in our flattr account, and we were planning on closing down our account.

**Comment by kparal** [comment]
Thanks for clarifying. That's unfortunate. I very much prefer Flattr to Paypal. It works better for microtransactions (Paypal fees are too high) and managing regular payments to many projects is easier.
