### ISSUE TITLE
Add a warning when owned/wished items highlighting is turned on, but not logged into Steam store

### ISSUE THREAD

**Issue by fratt** [SteamDatabase/SteamDatabase#368]
Wishlisted items highlighting is not working (at least for my account)

My Steam login is : na7as@mailfloor.ch

Could you have a look ?

**Comment by xPaw** [comment]
Are you using our browser extension? Are you logged in to steam store?

**Comment by fratt** [comment]
I was not logged into steam store ! It works now!
I had no idea it was required, maybe the extension can display a warning when you are not? It was really not clear.

Thank you !

**Comment by xPaw** [comment]
Yeah, that's a good idea, I've renamed and reopened this issue.

**Comment by xPaw** [comment]
Added a warning, will look like this:
![2015-08-12_13-19-23](https://cloud.githubusercontent.com/assets/613331/9221710/09f9f08a-40f5-11e5-95af-5638a5e77b83.png)
