### ISSUE TITLE
Donation Error

### ISSUE THREAD

**Issue by WtFKilla** [SteamDatabase/SteamDatabase#370]
i donate 2€ for the Page but i get the Error
"Error
Invalid CSRF token."

![ss 2015-08-16 at 05 14 15](https://cloud.githubusercontent.com/assets/9697969/9291815/bbad9f9c-43d5-11e5-9b73-a30f0abab360.png)

**Comment by xPaw** [comment]
Did this happen after you got redirected back from PayPal, or you did something after?

Your donation did go through by the way.

**Comment by xPaw** [comment]
Fixed.
