### ISSUE TITLE
Get rid of /myapps/ in favor of calculator

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/SteamDatabase#376]
And move sync button to /user/

**Comment by xPaw** [comment]
Done.

**Comment by Scrxtchy** [comment]
gg

![](http://link-removed.link/i/2015/08/15-08-31_11-14-44.png)
![](http://link-removed.link/i/2015/08/15-08-31_11-15-51.png)

**Comment by xPaw** [comment]
Good catch, fixed.
