### ISSUE TITLE
Extension crashes all firefox tabs when using Electrolysis

### ISSUE THREAD

**Issue by PedroHLC** [SteamDatabase/SteamDatabase#380]
I'm using firefox developer edition with SteamDatabase extension and Electrolysis (multiprocess) on.
When I open this page for example: https://steamdb.info/sales . It loads without the extension's filter options and a little time after, all the tab crashes...

**Comment by xPaw** [comment]
Well then report it to Mozilla.

**Comment by PedroHLC** [comment]
Electrolysis It's actually something that the extensions will have to adapt to.... Different API for changing page contents, etc...

**Comment by xPaw** [comment]
If an addon crashes all the tabs, then it's a browser issue. I'm not going to deal with another bullshit Mozilla change.

**Comment by xPaw** [comment]
Also, it seems to work fine for me with e10s, it doesn't crash.
