### ISSUE TITLE
Hovering over rating % shifts it to the left slightly in Chrome

### ISSUE THREAD

**Issue by Bowzaa** [SteamDatabase/SteamDatabase#390]
Tested in:
Chrome version 46.0.2490.80 m
Firefox 40.0.3, 41.0.1, 41.0.2
IE 9, 10

This only happens in Chrome from what I see, only tried on my personal computer, with and without extensions.

I recorded a 6 second .mp4 of the problem here http://puu.sh/l2grr.mp4

**Comment by xPaw** [comment]
CSS magic ¯\_(ツ)_/¯

**Comment by xPaw** [comment]
Fixed by removing whitespace in `<span>`.

**Comment by Bowzaa** [comment]
Rad
