### ISSUE TITLE
Duplicate game announcements

### ISSUE THREAD

**Issue by TomasDuda** [SteamDatabase/SteamDatabase#395]
The date field [for example here](https://api.steampowered.com/ISteamNews/GetNewsForApp/v2/?format=json&appid=227300&maxlength=1&feeds=steam_release,steam_community_announcements) is changed when the announcement is edited. Ignore it, use only gid.

**Comment by xPaw** [comment]
Should be fixed now. I've deleted all announcements and re-fetching them now.
