### ISSUE TITLE
0 Games not played > ??? Games not played

### ISSUE THREAD

**Issue by klaymen** [SteamDatabase/SteamDatabase#398]
Hi there,

First of all, you did an amazing job. I have cleared my not played games list, and I got a little disappointed, when instead of the charming and expected "0%" three questionmark appeared. I'm not sure if this is a real bug or as per design, however, it is a bit bothering as a "reward" :)

Thanks for reading,
Klaymen

**Comment by xPaw** [comment]
What's your steamid?

**Comment by klaymen** [comment]
Wow, you are fast :) My id is klaymen1984.

**Comment by xPaw** [comment]
Fixed, thanks for pointing this out.

**Comment by klaymen** [comment]
Thanks, amazing job!
