### ISSUE TITLE
Average price vs. Average price per hour

### ISSUE THREAD

**Issue by klaymen** [SteamDatabase/SteamDatabase#403]
Hi there,

I'm not sure if this is a bug, but I'm a bit confused about the calculation of "Average price per hour". My "Hours on record" is around 605 and the "Total account value" is around 1666 USD, then my "Average price per hour" shouldn't be around 2,75 USD instead of the currently shown 14.25 USD? (My steam ID is klaymen1984)

Thanks,
Klaymen

**Comment by xPaw** [comment]
It adds up all your "price per hour", and then divides it by number of games you own.

**Comment by klaymen** [comment]
Thanks for the prompt and clarifying answer. I got it now :)

Klaymen
