### ISSUE TITLE
Steam [CSGO] inventory bug.

### ISSUE THREAD

**Issue by starixera** [SteamDatabase/SteamDatabase#404]
many of the CSGO players/users are facing any issues of not seeing their inventory after accepting the inventory in the inventory bag. it is visible on the profile but cannot be seen ingame and cannot be equipped. This issue is persisting from last 24 hours or so may be less but still have an inventory worth 280$ being unable to equip or cannot be seen ingame.

**Comment by xPaw** [comment]
This has nothing to do with SteamDB.
