### ISSUE TITLE
Add "Date comfirmed" column in Linux games list

### ISSUE THREAD

**Issue by seeeeew** [SteamDatabase/SteamDatabase#410]
I'd love to see when games were confirmed as working on Linux, e. g. to be able to find games that I've owned for years but that only recently added Linux support.

Currently I grep `git blame GAMES.json` in a clone of the SteamLinux repo and compare the results with a list of my games, which seems like too much work.

**Comment by xPaw** [comment]
We don't really keep track of when games were confirmed, it would be equal amount of effort to implement this too.

**Comment by seeeeew** [comment]
Okay, then I'll just automate my current way. ^^

**Comment by xPaw** [comment]
Went ahead and did it. Set all times to what git blame produced.

**Comment by seeeeew** [comment]
Thanks, just what I wanted! I think for confirmed games this information is way more useful than the date of the last update. :+1:
