### ISSUE TITLE
Backend Full run not working

### ISSUE THREAD

**Issue by HantraxHat** [SteamDatabase/SteamDatabase#412]
Hey, i just compiled the last version of the backend and the full run update doesn't work (it doesn't also with older version).

23:16:31 [INFO] PICSChanges: Doing a full run on all apps and packages in the database.
23:16:31 [INFO] PICSChanges: Requesting info for 0 apps and 0 packages

**Comment by DoctorMcKay** [comment]
Valve broke it.

**Comment by xPaw** [comment]
Valve added a limit on that, so it no longer works.

**Comment by murray-mint** [comment]
Sorry to post in a closed bug, is there any workaround for populating an empty backend, or does someone have a SQL dump of a fully populated database that I could use?
