### ISSUE TITLE
Australian Dollar Option.

### ISSUE THREAD

**Issue by ryantheleach** [SteamDatabase/SteamDatabase#421]
You have New Zealand dollars as an option on https://steamdb.info/sales/?min_discount=75&min_rating=80 but any chance you could add the australian dollar region?

**Comment by SinZ163** [comment]
SteamDB has said multiple times, that they won't support it until steam recognises it as a separate currency and not just random price inflation (unfortunately)

**Comment by ryantheleach** [comment]
So is it really just random? or can I base decisions off of one of the other currencies like new zealand?

**Comment by SinZ163** [comment]
its up to publishers to decide how much Australia tax is applied afaik, and is wildly inconsistent with some games (like CS:GO) having no price difference, and others being +50%
