### ISSUE TITLE
Overwrite to https breaks searching by tag/genre

### ISSUE THREAD

**Issue by Kryzoid** [SteamDatabase/SteamDatabase#428]
**OS:** Windows 7 SP 1
**Chrome:** 48.0.2564.97 m
**Extension:** 1.5.4
  
Selecting the `Overwrite all http://steamcommunity.com links to be https` option makes searching unresponsive when switching pages. This happens on /tag/ and /genre/, but /search/ remains unaffected. Also tested on a different computer running Win10 and ran into the same issue.
  

- Recording of the problem **[here](https://www.youtube.com/watch?v=WsGhFeHjUaM)**

**Comment by xPaw** [comment]
https://github.com/SteamDatabase/SteamDatabase/compare/6e9693e7611cff33e56b2c1dce518f192f1b1212...4aa3754ecb1179d6309ef893ebdfa8ce0f2bfa0a
