### ISSUE TITLE
"You own this config, click to install"

### ISSUE THREAD

**Issue by PowerGamer1** [SteamDatabase/SteamDatabase#429]
There should not be a button to install non-apps like [https://steamdb.info/app/405630/info/](url) (button "Free" must not be present).

**Comment by xPaw** [comment]
It's free so you own it, doesn't make sense to hide the button.

**Comment by PowerGamer1** [comment]
And what sense does it make to install a "config" ?

**Comment by xPaw** [comment]
As silly it might seem, it's useful to have.

**Comment by PowerGamer1** [comment]
Useful for what exactly? Can you provide at least a single example?

**Comment by xPaw** [comment]
![steam_2016-01-31_14-43-54](https://cloud.githubusercontent.com/assets/613331/12702178/13944648-c829-11e5-83d7-34a826401b3d.png)

**Comment by PowerGamer1** [comment]
I don't think any "config" app is meant to be installed like that, Steam does not even show it afterwards in the "Library" tab and the resulting .acf has only shared depots:
```
    "MountedDepots"
	{
	}
	"SharedDepots"
	{
		"396221"		"396220"
		"396223"		"396220"
	}
```
I'd say this is still not useful at all.

**Comment by xPaw** [comment]
Just because you think it's not useful, doesn't mean it's not. If Steam lets you install it, the button will remain.

**Comment by PowerGamer1** [comment]
> If Steam lets you install it, the button will remain.

Alright, how about [https://steamdb.info/app/7/subs/](url) and [https://steamdb.info/app/8/subs/](url) and [https://steamdb.info/app/765/](url) and a whole bunch of others (which Steam WON'T let you install)?

IMO, the "functionality" provided by that install button is not supposed to exist in the first place (its just an oversight on Steam client part to even letting you successfully install some "config"s).

Regardless, in the end its your choice whether you want to improve your own website or not.

**Comment by xPaw** [comment]
If this button bothers you this much, use adblock to hide it.
