### ISSUE TITLE
Meta tags(description, og:description) Calculator Page has wrong data

### ISSUE THREAD

**Issue by dennydai** [SteamDatabase/SteamDatabase#430]
e.g. https://steamdb.info/calculator/76561198218729177/

Meta: DennyDai spent 107 hours playing **95%** of **my** games, valued at a total of $97
Web Page: Games not played: 585

So the Meta tag should be: DennyDai spent 107 hours playing **5%** of **his/her** games, valued at a total of $97

**Comment by xPaw** [comment]
Good catch, thanks.

Fixed.
