### ISSUE TITLE
Australia USD$ option

### ISSUE THREAD

**Issue by drtekrox** [SteamDatabase/SteamDatabase#432]
This issue is being raised again as it has come to my attention you now has a 'CIS $USD' option but are still yet to implement an Australia $USD to show the discrepancies in pricing here.

Can you please implement this feature or at least give reasonable explanation of why you won't?

**Comment by xPaw** [comment]
We will when Steam will.

**Comment by drtekrox** [comment]
Steam does already.
Only SteamDB doesn't.

add ?cc=au to the end of any store URL.

**Comment by xPaw** [comment]
Right, you meant USD. That's only a thing because it's a country specific override, but you still pay in USD. SteamDB will only use currencies that are supposed by Steam, and Australian dollar is not.
