### ISSUE TITLE
Removed games keeps trying to install

### ISSUE THREAD

**Issue by Sjvedik** [SteamDatabase/SteamDatabase#437]
I had some updates that keept downloading,veifying, then moving on to next, and when all my 4 updates had downloaded, they started over, but never installed, but re-downloaded. There were no lack of drivespace. So I just removed the installed games with "delete local content".

Problem is that when steam starts it STILL is allocating data and downloading theese updates, and it keeps doing it no matter how many times I cancel them and re-removes local data for those games.

Current games with that problem for me is Subnautica, ARK survival evolved, Life is feudal, and Unturned. Is there a way to manually edit the downloadlist for steamapp updates to fix this?
Why did those updates keep failing to install?

**Comment by xPaw** [comment]
We're not Valve.
