### ISSUE TITLE
Sorting on bundles page

### ISSUE THREAD

**Issue by ahmedtds** [SteamDatabase/SteamDatabase#442]
Hi. I think it would be useful if we could sort bundles in this page: https://steamdb.info/bundles/

Also would you consider integrating these bundles into sales page?

**Comment by xPaw** [comment]
These bundles don't have any real sales, the discount is preset and always kept, so there's not much point in displaying these on sales page.

**Comment by xPaw** [comment]
:ship: Added table sorting.
