### ISSUE TITLE
SteamDB Extension causes infinite loop on Steam Age Check

### ISSUE THREAD

**Issue by Black3ird** [SteamDatabase/SteamDatabase#443]
Hello,

Only SteamDB v1.5.7 extension on empty/clean FireFox profile when visiting an age check required Steam page like http://store.steampowered.com/app/447040/ (WD2) causes page load stuck at http://store.steampowered.com/agecheck/app/447040/ indefinitely. For trying this your Steam cookie must not have verified age check, otherwise it goes smooth after it is recorded in cookie. So either clean cookies or try it on new clean profile.

As a workaround, extension can be turned off/on on the fly without restart to go through age check successfully. Hoping this will get addressed on next release.

Regards.

**Comment by jimmydorry** [comment]
Pretty sure it was already updated... 

https://addons.mozilla.org/en-US/firefox/addon/steam-database/versions/?page=1#version-1.5.8
