### ISSUE TITLE
Top Game Owners: Awkward wording in page description

### ISSUE THREAD

**Issue by jimmydorry** [SteamDatabase/SteamDatabase#445]
http://i.imgur.com/vZOvrht.png

**You have:** "Lookup a profile using our Steam calculator to update it, and a chance to appear in this list."

It looks awkward, and the feeble minded users may (incorrectly) be led to believe that this list boils down chance.

**Alternative wording example:** "Lookup a profile in our Steam calculator to update its badge levels."

OR

**Alternative wording example:** "Badge levels are cached. Update a profile by looking it up in our Steam calculator."

**Comment by xPaw** [comment]
:ship:

**Comment by jimmydorry** [comment]
:astonished:
