### ISSUE TITLE
Spore: Creepy & Cute Parts Pack

### ISSUE THREAD

**Issue by Unicorn437** [SteamDatabase/SteamDatabase#447]
https://steamdb.info/calculator/76561198010040646/
The game Spore: Creepy & Cute Parts Pack is a DLC that I cannot start manually, yet it is listed as a game I haven't played yet. Its also listing way too many games as not played, I'm counting 18 on the website while it displays a whacking 48.

**Comment by xPaw** [comment]
That's out of our control. App 17440 is reported as a game, and API reports your playtime for that as 0.
