### ISSUE TITLE
Games not played counts DLC

### ISSUE THREAD

**Issue by adomas187** [SteamDatabase/SteamDatabase#448]
Hello,
I found this issue, in Steam Calculator. From my Steam Library I have played all games at least 5min (less than that counts as not played), and anyway I have written "_1 Games not played_" and "_1% Games not played_". This seems to be related to:
_**Age of Empires II HD: The African Kingdoms**_
AppID: 355950, **DLC**
And I HAVE played it, but as it is a part of Age of Empires II HD, somehow it does not count separately play time. Why does DLC counts as Not Played game? It's part of game, but not game itself.

The reason of this, I wanted to be sure I have tried all my Steam Library games, but however I can't reach 0% Games not played, because of this DLC. Is it a bug? I think so, but not sure.

**Comment by xPaw** [comment]
> Why does DLC counts as Not Played game

DLC is the keyword, it can't have playtime unless it is a separate game. We use all the available data that the Steam API provides, it's not really in our control.
