### ISSUE TITLE
"Games not played" count is immensely wrong

### ISSUE THREAD

**Issue by AWGEnough** [SteamDatabase/SteamDatabase#453]
The "Games not played" count on my profile says I never played 582 games (~20% of total).
Actually the right number is 17 (>1%, and among them there are 5 DLCs and 5 videos so the actual number is even smaller).
How's this? Is it a bug or am I missing something out? Thanks.

**Comment by xPaw** [comment]
Do all these games have gameplay of less than 5 minutes?

**Comment by AWGEnough** [comment]
Less than 5 minutes is considered "not played"?

**Comment by xPaw** [comment]
Our code doesn't consider them played, yes.
