### ISSUE TITLE
Sales Page -Toggling 'Hide Owned Games' checkbox without changing anything else does not make the reload button available

### ISSUE THREAD

**Issue by KPJoshi** [SteamDatabase/SteamDatabase#454]
Title should be self explanatory.
Happens in Firefox and Chrome, latest versions.

**Comment by xPaw** [comment]
This option works on page, there is no need to reload.

**Comment by KPJoshi** [comment]
I see. However, it is not intuitive, considering that changing pretty much anything else requires a reload. I keep getting confused as to why I don't get the option to do so.

**Comment by xPaw** [comment]
Yeah that's true. Unsure if there is an easy way to fix that.

**Comment by KPJoshi** [comment]
A simple solution: when you just toggle 'hide owned games' and make no other changes, make the text on the button 'reload not necessary' or something.

**Comment by xPaw** [comment]
Added a tooltip.
