### ISSUE TITLE
Failed to load your games. Unexpected token 'a', "array(499)"... is not valid JSON

### ISSUE THREAD

**Issue by ckykenken** [SteamDatabase/SteamDatabase#806]
- _Browser name and version:_ Google Chrome 115.0.5790.171
- _Device (mobile or desktop):_ Desktop Windows 10 22H2
- _Page where the issue happens:_ https://steamdb.info/freepackages/

### Describe the bug
Self-explanatory
![image](https://github.com/SteamDatabase/steamdb.info-issues/assets/26035978/9756110a-b4bf-4675-b289-7491cea90aa2)

**Comment by KyleStilkey** [comment]
Similar issue as you with all browsers tested resulting in a Failed to load your games. Unexpected token 'a', "array(448)"... is not valid JSON.

UPDATE: Looks like this is due to Valve making some changes today that may have broken this. Will have to wait for them to fix this.
