### ISSUE TITLE
Copy Epoch Datetime

### ISSUE THREAD

**Issue by Lordfirespeed** [SteamDatabase/SteamDatabase#812]
### Feature Description

Some way to copy the epoch timestamp of a table row's datetime to clipboard. 

For example, https://steamdb.info/app/1966720/patchnotes/
![image](https://github.com/SteamDatabase/steamdb.info-issues/assets/28568841/7f9d9a21-1782-4745-b00c-505250d057bb)

It seems in this particular case, the timestamp is available in the HTML source for each row: `<tr data-date="1702209855"> ... </tr>`
It'd be really awesome if there were some way to grab that timestamp without having to inspect element. 

Perhaps a small 'clock' icon to the right of the datetime that can be clicked?

**Comment by xPaw** [comment]
Why?

**Comment by Lordfirespeed** [comment]
Why not?

**Comment by Lordfirespeed** [comment]
I'm sorry if this feature request offended you in some way. Thankyou for all your incredible work on SteamDB, the work you've done for the community has always been really impressive to me. 

My particular use-case is that I'm writing an app where it is helpful to associate a build ID and its update time to an 'in-game' version, and I get the data for past build IDs and their update times from SteamDB as they aren't available from SteamCMD.

I opened a feature request because I know it is a feature that I would use, and I wasn't under the impression that there were any requirements for a feature's popularity prior to opening a request. 

I would be very happy to contribute (provided that is an option; I understand if not) if you don't think this feature is worth your team's time.

**Comment by xPaw** [comment]
Don't automate against SteamDB, automate against Steam directly, then you can get build times from appinfo yourself. https://steamdb.info/faq/#how-are-we-getting-this-information

**Comment by Lordfirespeed** [comment]
I have no desire to automate against SteamDB. I was retrieving values from the site manually, because I only retrieve the metadata I need for each version once. I wouldn't need the described feature if I were automating against SteamDB.

I previously thought it wasn't possible to retrieve a list of past build IDs / manifest IDs directly from Steam.
Do you know, offhand, whether SteamKit is able to do that? ( Please don't waste your own time investigating, I can do so myself, but if you happen to know then it would save me some time ).

**Comment by xPaw** [comment]
You could do get times by making a user script or something, I don't think the button is needed here.

For a steam bot, you would have track updates going forward.

**Comment by Lordfirespeed** [comment]
> You could do get times by making a user script or something, I don't think the button is needed here.

Oh, I thought using a user script for that would be disallowed by the 'scraping' rule. 

> For a steam bot, you would have track updates going forward.

Yes, I thought so. Okay. Thanks very much for your help.
