### ISSUE TITLE
"Walkabout Mini Golf VR" Missing From Charts

### ISSUE THREAD

**Issue by JoshFyneHartInd** [SteamDatabase/SteamDatabase#813]
- _Browser name and version:_ Chrome 120.0.6099.111
- _Device (mobile or desktop):_ Desktop, Windows 10
- _Page where the issue happens:_ https://steamdb.info/charts/

I can't get Walkabout Mini Golf VR (https://steamdb.info/app/1408230/) to show up in any lists. I can manually search for it and see that it is tagged correctly (tracked controller, VR only, etc) but when looking through charts, it doesn't show up. I've tried filtering by category and tag as well as no filtering.

I am not logged in on the site when I'm trying.

**Comment by xPaw** [comment]
It's filtered by default, there's link at the bottom to view all (requires sign in I think).

**Comment by JoshFyneHartInd** [comment]
Why is it filtered? is there a list of filtered games?

**Comment by xPaw** [comment]
Not enough players.
