### ISSUE TITLE
Track historical data of the Steam Hardware & Software Survey

### ISSUE THREAD

**Issue by Kruchji** [SteamDatabase/SteamDatabase#814]
### Feature Description

Would it be possible to create a page that would display all historical data from the [Steam Hardware & Software Survey](https://store.steampowered.com/hwsurvey)?

Valve only shows data from the past year and a half. While older data can be found using the Wayback Machine, it is a bit inconvenient (and not all in one graph).

**Comment by xPaw** [comment]
https://web.archive.org/web/20230801000000*/https://store.steampowered.com/hwsurvey
