### ISSUE TITLE
Protobufs use

### ISSUE THREAD

**Issue by anywhereyang** [SteamDatabase/SteamDatabase#815]
### Feature Description

'm setting up a WSS (WebSocket Secure) server and modifying the WSS connection used by the Steam client during login to point to my server's address. The purpose is to enter an incorrect password during login and then modify it to the correct password on my server. After that, I want to establish a connection from my server to the Steam server and send the modified binary data to the Steam server, effectively protecting the password. In previous versions of the Steam client, it was possible to modify passwords directly as they were transmitted in plaintext. However, in the newer versions, passwords are encrypted, and Steam now uses gRPC. Is it currently possible to achieve the desired result? I'm using C++ and would appreciate any assistance you can provide

**Comment by xPaw** [comment]
This is unrelated to steamdb
