### ISSUE TITLE
Filters on "instantsearch" don't work

### ISSUE THREAD

**Issue by 6Fv** [SteamDatabase/SteamDatabase#819]
1. The [Stardew Valley](https://steamdb.info/app/413150/) game contains the "Co-op" tag.
![0](https://github.com/SteamDatabase/steamdb.info-issues/assets/88627467/16f2d9d9-b0f7-4625-a1a6-922fbb6ff47c)

2. The [Stardew Valley](https://steamdb.info/app/413150/) game is 3rd, with ~97.39%, on the [instantsearch](https://steamdb.info/instantsearch/) page.
![1](https://github.com/SteamDatabase/steamdb.info-issues/assets/88627467/4c748340-47d7-4677-9a1e-8a5c976d616f)

3. After applying the "Co-op" tag, the [Stardew Valley](https://steamdb.info/app/413150/) game no longer appears.
![2](https://github.com/SteamDatabase/steamdb.info-issues/assets/88627467/c02b6838-846a-42c7-8ac5-f00b047dacfe)

**Comment by xPaw** [comment]
You're trying to filter by tag which are applied devs/players, but the Co-op you're showing is a category which you can filter under Number of Players.

(as to why there's a conflicting category and tag -- ask valve)

**Comment by 6Fv** [comment]
Ah! Much appreciated, thanks.
