### ISSUE TITLE
Did Not Connect: Potential Security Issue

### ISSUE THREAD

**Issue by SilverFang13** [SteamDatabase/SteamDatabase#825]
- _Browser name and version:_ Floorp: Version 11.12.2 (64-bit) & Firefox: Version 125.0.3 (64-bit)
- _Device (mobile or desktop):_ Desktop (website)
- _Page where the issue happens:_ All

### Describe the bug

Anytime I try to connect to the SteamDB.info site I get the pictured error. I have tried disabling every extension and change to my network on both browsers and also tried un and re installing firefox and still get this error

### Extensions:
DuckDuckGo Privacy Essentials
Privacy Badger
uBlockOrigin

### Network:
NextDNS
NordVPN

![Screenshot 2024-05-11 155541](https://github.com/SteamDatabase/steamdb.info-issues/assets/151080138/2789a27a-b554-4521-8f3a-a842429289b3)
![Screenshot 2024-05-11 155551](https://github.com/SteamDatabase/steamdb.info-issues/assets/151080138/8798b064-fcad-4b63-9f92-940a83cc6132)

**Comment by xPaw** [comment]
That's a problem on your end.

**Comment by SilverFang13** [comment]
what am I to do to fix this?? I have found very little information online and spent over an hour now trobleshooting
