### ISSUE TITLE
Cyberpunk 2077: Ultimate Edition incorrect discount number

### ISSUE THREAD

**Issue by QuickWick123** [SteamDatabase/SteamDatabase#828]
- _Page where the issue happens:_ https://steamdb.info/bundle/32470/

### Describe the bug
The discount number is reporting 43% off but it is really 38% off. Price is reported correctly.

**Comment by xPaw** [comment]
![Screenshot_2024-05-17-00-43-13-47_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/SteamDatabase/steamdb.info-issues/assets/613331/43c67be7-2a35-4571-972d-26117400fdf7)

**Comment by QuickWick123** [comment]
![image](https://github.com/SteamDatabase/steamdb.info-issues/assets/78274206/d025f878-eac9-4de5-8c47-1a362f72441f)

**Comment by QuickWick123** [comment]
![image](https://github.com/SteamDatabase/steamdb.info-issues/assets/78274206/c2c8e243-e91f-43f9-b00d-dc2913718897)

**Comment by QuickWick123** [comment]
![image](https://github.com/SteamDatabase/steamdb.info-issues/assets/78274206/907ffe50-9425-49c8-b47f-bedb3914bb13)

**Comment by QuickWick123** [comment]
Seems like its a steam cart issue.
