### ISSUE TITLE
Left menu could be more dynamic

### ISSUE THREAD

**Issue by Tiagoquix** [SteamDatabase/SteamDatabase#830]
For example:

https://steamdb.info/app/730/

The left menu:

![image](https://github.com/SteamDatabase/steamdb.info-issues/assets/30274161/5446cca4-799d-45b4-b12a-9fdc6de6b6b7)

could be more dynamic instead of being fixed at the bottom. It could be initially displayed at the top

![image](https://github.com/SteamDatabase/steamdb.info-issues/assets/30274161/21200c13-61ca-4d90-8e9d-f62bb3e64ab6)

and then it would dynamically auto-adjust itself based on user scrolling.

This would make it more intuitive and better to navigate IMO.

Thanks in advance.

**Comment by xPaw** [comment]
The top part of the page does not change between tabs, so that would be more confusing. I tried this before.
