### ISSUE TITLE
Sales pages currency filter not saving

### ISSUE THREAD

**Issue by ghost** [SteamDatabase/SteamDatabase#831]
- _Browser name and version:_ 
- Firefox 126.0.1
- _Device (mobile or desktop):_ 
- Desktop
- _Page where the issue happens:_ 
- https://steamdb.info/sales/

### Describe the bug

When selecting a currency filter on the sales page, the selected currency will often not save between page loads. Sometimes it changes with a simple refresh, other times when opened in a new tab. I can't see any consistent reasoning behind it, and the currency it changes to also seems to be random.

This feature and all the other settings saved perfectly previously.

**Comment by xPaw** [comment]
It sets a cookie with a country you selected. If you change it elsewhere (e.g. by opening another url with cc in the param), it can change.

Unless you can point me to a specific repro where it's being reset incorrectly, this is not a bug.

> This feature and all the other settings saved perfectly previously.

Sounds like you changed something in your Firefox.
