### ISSUE TITLE
Trivial/cosmetic: [Steam Install] vs. [Steam Library]

### ISSUE THREAD

**Issue by Yujah** [SteamDatabase/SteamDatabase#838]
- _Browser name and version:_ All
- _Device (mobile or desktop):_ All
- _Page where the issue happens:_  F.e. https://steamdb.info/app/3830/ufs/

Trivial/cosmetic, but I just noticed that e.g. on the above page, "Save File Locations"are specified as e.g.

[Steam Install]/steamapps/common/Psychonauts/profiles/profile 1

In f.e. my case my [Steam Install] is the standard C:\Program Files  (x86)\Steam whereas I have Psychonauts installed in

D:\SteamLibrary\steamapps\common\Psychonauts.

Seems it'd be a bit better to have that template say [Steam Library] or alike rather than [Steam Install], that is. FWIW.

**Comment by xPaw** [comment]
Fair. I used Steam Install because that's what Steam's docs use, but library makes more sense.

**Comment by Yujah** [comment]
Heh. That is certainly fast. Cheers :)
