### ISSUE TITLE
Patch notes RSS feed fails validation

### ISSUE THREAD

**Issue by bitingsock** [SteamDatabase/SteamDatabase#839]
For example:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fsteamdb.info%2Fapi%2FPatchnotesRSS%2F%3Fappid%3D1086940

**Comment by xPaw** [comment]
Does some actual RSS reader fail to parse it?

**Comment by bitingsock** [comment]
Thunderbird, Feedbro
both fail

**Comment by xPaw** [comment]
![image](https://github.com/user-attachments/assets/86cf4899-c157-4572-a71f-17d61cacd84b)

Works for me in Thunderbird.
