### ISSUE TITLE
Detect Denuvo Anti-Tamper and Denuvo Anti-Cheat as a "Technology"

### ISSUE THREAD

**Issue by Tiagoquix** [SteamDatabase/SteamDatabase#840]
### Feature Description

Denuvo Anti-Tamper and Denuvo Anti-Cheat could be detected by SteamDB to appear in the "Technologies" field.

Detection would probably be by scanning the 3rd-party DRM list for `Incorporates 3rd-party DRM: Denuvo`.

Example of a game that has Denuvo: https://store.steampowered.com/app/2358720/Black_Myth_Wukong/ | https://steamdb.info/app/2358720/

**Comment by xPaw** [comment]
> 3rd-Party DRM	Denuvo

It's already detected. You can use this link if you want to see a list: https://steamdb.info/search/?a=app_keynames&type=-1&keyname=427&operator=1&keyvalue=Denuvo&display_value=on

**Comment by Tiagoquix** [comment]
@xPaw Thanks. My idea is to also make them appear in the "Technologies" field, which they don't do currently.
