### ISSUE TITLE
Option to skip deals without expiry date at the sales page

### ISSUE THREAD

**Issue by enchained** [SteamDatabase/SteamDatabase#845]
### Feature Description
During the large sales often some games do not have an expiry date for a while (or until the last day). Also, when the sale is long, like the Winter sale, some discounts end a few days early, but there's no way to properly check this for now even using the Ends sorting. For example, to see that DLCs to Songs of Conquest and Sands of Salzaar ends tomorrow instead of Jan 2nd, I had to scroll and click the next page until the 49 (out of 63 pages total). I can't imagine how far would I have to click to reach that point for the base game sales page, but from the other sources it looks like at least a couple dozen discounts end today, tomorrow, etc.

### Proposed solutions
Option 1: checkmark "hide unknown expiry deals" in filters
Option 2: better pagination that allows to skip pages in bulk, or enter/click the specific page number.

**Comment by xPaw** [comment]
Just sort by expiry.

**Comment by xPaw** [comment]
I've added a fallback during major sales so that it puts expires to the sale end date, this improves sorting.

https://steamdb.info/sales/?sort=ends_asc

**Comment by enchained** [comment]
> Just sort by expiry.

That's what I did from the start, still had to click through 49 DLC pages with no expiry cause it goes first in that sorting.

> I've added a fallback during major sales so that it puts expires to the sale end date, this improves sorting.

Thank you so much, it indeed improved greatly. Does those games have a specific major sale marker, or is it just applied to everything with no expiry that is up during a major sale?

**Comment by xPaw** [comment]
Just everything. You can increase how many games you see per page btw.
