### ISSUE TITLE
Open external links in new tab

### ISSUE THREAD

**Issue by Botan626** [SteamDatabase/SteamDatabase#846]
### Feature Description
for convenience to prevent losing `steamdb.info` site

like these ones:
![image](https://github.com/user-attachments/assets/6ecb5e1b-13bd-422d-8807-60f98a8982ec)

**Comment by xPaw** [comment]
Middle click them.

**Comment by Botan626** [comment]
> Middle click them.

that is inconvenience

all sane websites do that
